# Resolve managed dependencies from the checked-in dependencies.json. A
# matching resolved entry needs no Python or network. Overrides are resolved
# into the build tree so configuring a consumer never edits Aria's checkout.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/ariaFindQt.cmake")

foreach(_aria_dep JSON DOCTEST MIRA OPENSSL)
    set(ARIA_DEP_${_aria_dep}_VERSION "" CACHE STRING
        "Explicit ${_aria_dep} version (empty: use dependencies.json)")
endforeach()
unset(_aria_dep)
option(ARIA_DEPENDENCIES_OFFLINE "Require locked dependency metadata and cached downloads" OFF)
set(ARIA_DEPENDENCIES_FILE "" CACHE FILEPATH "Consumer dependencies.json (empty: Aria's file)")

# Shared with scripts/dependencies.py: flat string fields, sorted by key,
# encoded as UTF-8 byte-length-prefixed key/value pairs. Exclude resolved so
# request metadata is stored once without losing stale-resolution detection.
function(_aria_dependency_request_hash specification result)
    string(JSON _type ERROR_VARIABLE _error TYPE "${specification}")
    if(_error OR NOT _type STREQUAL "OBJECT")
        message(FATAL_ERROR "Aria deps: dependency specification must be an object")
    endif()
    string(JSON _length LENGTH "${specification}")
    set(_keys "")
    if(_length GREATER 0)
        math(EXPR _last "${_length} - 1")
        foreach(_index RANGE 0 ${_last})
            string(JSON _key MEMBER "${specification}" ${_index})
            if(NOT _key STREQUAL "resolved")
                list(APPEND _keys "${_key}")
            endif()
        endforeach()
    endif()
    list(SORT _keys)
    set(_preimage "aria-dependency-request-v1\n")
    foreach(_key IN LISTS _keys)
        string(JSON _type TYPE "${specification}" "${_key}")
        if(NOT _key MATCHES "^[a-z][a-z0-9_]*$" OR NOT _type STREQUAL "STRING")
            message(FATAL_ERROR "Aria deps: specification keys must be lowercase identifiers with string values")
        endif()
        string(JSON _value GET "${specification}" "${_key}")
        string(LENGTH "${_key}" _key_length)
        string(LENGTH "${_value}" _value_length)
        string(APPEND _preimage "${_key_length}:${_key}${_value_length}:${_value}")
    endforeach()
    string(SHA256 _hash "${_preimage}")
    set(${result} "${_hash}" PARENT_SCOPE)
endfunction()

function(_aria_dependency_resolved_entry file name request_hash requested explicit base_hash valid entry)
    set(${valid} FALSE PARENT_SCOPE)
    if(NOT EXISTS "${file}")
        return()
    endif()
    file(READ "${file}" _document)
    string(JSON _schema ERROR_VARIABLE _error GET "${_document}" schema)
    if(_error OR NOT _schema STREQUAL "2")
        message(FATAL_ERROR "Aria deps: invalid schema in dependency file '${file}'")
    endif()
    if(NOT base_hash STREQUAL "")
        string(JSON _base_hash ERROR_VARIABLE _error GET "${_document}" _base_sha256)
        if(_error OR NOT _base_hash STREQUAL base_hash)
            return()
        endif()
    endif()
    string(JSON _spec ERROR_VARIABLE _error GET "${_document}" dependencies "${name}")
    if(_error)
        return()
    endif()
    _aria_dependency_request_hash("${_spec}" _hash)
    if(NOT _hash STREQUAL request_hash)
        return()
    endif()
    string(JSON _entry ERROR_VARIABLE _error GET "${_spec}" resolved)
    if(_error)
        return()
    endif()
    string(JSON _hash ERROR_VARIABLE _error GET "${_entry}" request_hash)
    if(_error OR NOT _hash STREQUAL request_hash)
        return()
    endif()
    if(explicit)
        string(JSON _requested ERROR_VARIABLE _error GET "${_entry}" requested)
        string(JSON _version ERROR_VARIABLE _version_error GET "${_entry}" version)
        string(JSON _tag ERROR_VARIABLE _tag_error GET "${_entry}" tag)
        if(_error OR _version_error)
            return()
        endif()
        if(_tag_error)
            set(_tag "")
        endif()
        if(NOT requested STREQUAL _requested AND NOT requested STREQUAL _version
           AND NOT requested STREQUAL _tag)
            return()
        endif()
    endif()
    set(_fields requested version url)
    string(JSON _provider GET "${_spec}" provider)
    if(_provider STREQUAL "github")
        list(APPEND _fields tag revision)
    endif()
    foreach(_field IN LISTS _fields)
        string(JSON _value ERROR_VARIABLE _error GET "${_entry}" "${_field}")
        string(JSON _type ERROR_VARIABLE _type_error TYPE "${_entry}" "${_field}")
        if(_error OR _type_error OR NOT _type STREQUAL "STRING" OR _value STREQUAL "")
            message(FATAL_ERROR "Aria deps: invalid ${name}.${_field} in '${file}'")
        endif()
    endforeach()
    string(JSON _url GET "${_entry}" url)
    if(NOT _url MATCHES "^https://[^/?#@ \t\r\n]+([/?#].*)?$")
        message(FATAL_ERROR "Aria deps: ${name}.url must use HTTPS without credentials in '${file}'")
    endif()
    if(_provider STREQUAL "github")
        string(JSON _revision GET "${_entry}" revision)
        string(LENGTH "${_revision}" _length)
        if(NOT _length EQUAL 40 OR NOT _revision MATCHES "^[0-9a-fA-F]+$")
            message(FATAL_ERROR "Aria deps: ${name}.revision must be a full commit SHA in '${file}'")
        endif()
    endif()
    string(JSON _artifact GET "${_spec}" artifact)
    if(NOT _artifact STREQUAL "git")
        string(JSON _sha ERROR_VARIABLE _error GET "${_entry}" sha256)
        string(LENGTH "${_sha}" _length)
        if(_error OR NOT _length EQUAL 64 OR NOT _sha MATCHES "^[0-9a-fA-F]+$")
            message(FATAL_ERROR "Aria deps: ${name}.sha256 must be a SHA256 in '${file}'")
        endif()
    endif()
    set(${valid} TRUE PARENT_SCOPE)
    set(${entry} "${_entry}" PARENT_SCOPE)
endfunction()

# aria_resolve_dependency(NAME json VERSION version URL url SHA256 hash
#                         [REVISION commit] [TAG tag] [FILE path])
# Output arguments name variables in the caller's scope. NAME is case insensitive.
function(aria_resolve_dependency)
    cmake_parse_arguments(DEP "" "NAME;VERSION;URL;SHA256;REVISION;TAG;FILE" "" ${ARGN})
    if(NOT DEP_NAME OR DEP_UNPARSED_ARGUMENTS OR DEP_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "aria_resolve_dependency: expected NAME and output-variable arguments")
    endif()
    string(TOLOWER "${DEP_NAME}" _name)
    string(TOUPPER "${DEP_NAME}" _upper)
    if(NOT DEP_FILE AND ARIA_DEPENDENCIES_FILE)
        set(DEP_FILE "${ARIA_DEPENDENCIES_FILE}")
    endif()
    if(NOT DEP_FILE)
        set(DEP_FILE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../dependencies.json")
    endif()
    get_filename_component(DEP_FILE "${DEP_FILE}" ABSOLUTE)
    if(NOT EXISTS "${DEP_FILE}")
        message(FATAL_ERROR "Aria deps: dependency file does not exist: ${DEP_FILE}")
    endif()
    file(READ "${DEP_FILE}" _document)
    string(JSON _schema ERROR_VARIABLE _error GET "${_document}" schema)
    if(_error OR NOT _schema STREQUAL "2")
        message(FATAL_ERROR "Aria deps: invalid dependency schema: ${DEP_FILE}")
    endif()
    string(JSON _spec ERROR_VARIABLE _error GET "${_document}" dependencies "${_name}")
    if(_error)
        message(FATAL_ERROR "Aria deps: '${_name}' is not in ${DEP_FILE}")
    endif()
    _aria_dependency_request_hash("${_spec}" _request_hash)
    set(_requested "${ARIA_DEP_${_upper}_VERSION}")
    set(_explicit TRUE)
    if(_requested STREQUAL "")
        string(JSON _requested ERROR_VARIABLE _error GET "${_spec}" version)
        if(_error OR _requested STREQUAL "" OR _requested STREQUAL "latest")
            set(_requested latest)
            set(_explicit FALSE)
        endif()
    endif()
    # Track the source even when it satisfies this request. Removing a later
    # resolved entry must not resurrect an earlier effective selection.
    string(SHA256 _identity "${DEP_FILE}")
    string(SUBSTRING "${_identity}" 0 16 _identity)
    set(_directory "${CMAKE_BINARY_DIR}/deps/aria-${_identity}")
    file(MAKE_DIRECTORY "${_directory}")
    file(LOCK "${_directory}/.cmake-resolve.lock" GUARD FUNCTION TIMEOUT 180)
    set(_effective "${_directory}/dependencies.json")
    file(SHA256 "${DEP_FILE}" _base_hash)
    set(_state "${_base_hash}\n")
    set(_previous_state "")
    if(EXISTS "${_directory}/base-state")
        file(READ "${_directory}/base-state" _previous_state)
    endif()
    if(NOT _state STREQUAL _previous_state)
        file(REMOVE "${_effective}")
        file(WRITE "${_directory}/base-state" "${_state}")
    endif()
    _aria_dependency_resolved_entry("${DEP_FILE}" "${_name}" "${_request_hash}"
        "${_requested}" "${_explicit}" "" _valid _entry)
    if(NOT _valid)
        # Retain the effective selection across configure runs only while
        # its source dependencies.json stays unchanged.
        _aria_dependency_resolved_entry("${_effective}" "${_name}" "${_request_hash}"
            "${_requested}" "${_explicit}" "${_base_hash}" _valid _entry)
        if(NOT _valid)
            find_package(Python3 3.10 QUIET COMPONENTS Interpreter)
            if(NOT Python3_Interpreter_FOUND)
                message(FATAL_ERROR
                    "Aria deps: resolving ${_name} (${_requested}) requires Python 3.10+. "
                    "A matching resolved entry in dependencies.json builds without Python.")
            endif()
            set(_arguments resolve --file "${DEP_FILE}" --output "${_effective}"
                --cache-dir "${_directory}/downloads" --only "${_name}")
            if(NOT "${ARIA_DEP_${_upper}_VERSION}" STREQUAL "")
                list(APPEND _arguments --version "${_name}=${ARIA_DEP_${_upper}_VERSION}")
            endif()
            if(ARIA_DEPENDENCIES_OFFLINE)
                list(APPEND _arguments --offline)
            endif()
            execute_process(COMMAND "${Python3_EXECUTABLE}"
                "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../scripts/dependencies.py" ${_arguments}
                RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
            if(NOT _result EQUAL 0)
                message(FATAL_ERROR "Aria deps: resolution failed for ${_name}:\n${_output}${_error}")
            endif()
            _aria_dependency_resolved_entry("${_effective}" "${_name}" "${_request_hash}"
                "${_requested}" "${_explicit}" "${_base_hash}" _valid _entry)
            if(NOT _valid)
                message(FATAL_ERROR "Aria deps: resolver did not produce matching resolved metadata for ${_name}")
            endif()
        endif()
    endif()
    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            "${DEP_FILE}")
        if(EXISTS "${_effective}")
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_effective}")
        endif()
    endif()
    foreach(_field VERSION URL SHA256 REVISION TAG)
        if(DEP_${_field})
            string(TOLOWER "${_field}" _key)
            string(JSON _value ERROR_VARIABLE _error GET "${_entry}" "${_key}")
            if(_error)
                message(FATAL_ERROR "Aria deps: ${_name} has no ${_key} in its resolved entry")
            endif()
            set(${DEP_${_field}} "${_value}" PARENT_SCOPE)
        endif()
    endforeach()
endfunction()
