# Resolve managed dependencies from the checked-in manifest and lock. A
# matching lock needs no Python or network. Version overrides are resolved
# into the build tree so configuring a consumer never edits Aria's checkout.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/ariaFindQt.cmake")

foreach(_aria_dep JSON DOCTEST MIRA OPENSSL)
    set(ARIA_DEP_${_aria_dep}_VERSION "" CACHE STRING
        "Explicit ${_aria_dep} version (empty: use the manifest and dependency lock)")
endforeach()
unset(_aria_dep)
option(ARIA_DEPENDENCIES_OFFLINE "Require locked dependency metadata and cached downloads" OFF)
set(ARIA_DEPENDENCY_MANIFEST "" CACHE FILEPATH "Consumer dependency manifest (empty: Aria's manifest)")
set(ARIA_DEPENDENCY_LOCK "" CACHE FILEPATH "Consumer dependency lock (empty: next to the manifest)")

function(_aria_dependency_lock_entry lock manifest name requested explicit valid entry)
    set(${valid} FALSE PARENT_SCOPE)
    if(NOT EXISTS "${lock}")
        return()
    endif()
    file(READ "${lock}" _lock)
    string(JSON _schema ERROR_VARIABLE _error GET "${_lock}" schema)
    if(_error OR NOT _schema STREQUAL "1")
        message(FATAL_ERROR "Aria deps: invalid schema in dependency lock '${lock}'")
    endif()
    string(JSON _entry ERROR_VARIABLE _error GET "${_lock}" dependencies "${name}")
    if(_error)
        return()
    endif()
    string(JSON _spec GET "${manifest}" dependencies "${name}")
    string(JSON _source ERROR_VARIABLE _error GET "${_entry}" source)
    if(_error OR NOT _source STREQUAL _spec)
        return()
    endif()
    if(explicit)
        string(JSON _requested ERROR_VARIABLE _error GET "${_entry}" requested)
        string(JSON _version ERROR_VARIABLE _version_error GET "${_entry}" version)
        string(JSON _tag ERROR_VARIABLE _tag_error GET "${_entry}" tag)
        if(_error OR _version_error)
            return()
        endif()
        if(_tag_error)
            set(_tag "")
        endif()
        if(NOT requested STREQUAL _requested AND NOT requested STREQUAL _version
           AND NOT requested STREQUAL _tag)
            return()
        endif()
    endif()
    set(_fields requested version url)
    string(JSON _provider GET "${_spec}" provider)
    if(_provider STREQUAL "github")
        list(APPEND _fields tag revision)
    endif()
    foreach(_field IN LISTS _fields)
        string(JSON _value ERROR_VARIABLE _error GET "${_entry}" "${_field}")
        string(JSON _type ERROR_VARIABLE _type_error TYPE "${_entry}" "${_field}")
        if(_error OR _type_error OR NOT _type STREQUAL "STRING" OR _value STREQUAL "")
            message(FATAL_ERROR "Aria deps: invalid ${name}.${_field} in '${lock}'")
        endif()
    endforeach()
    string(JSON _url GET "${_entry}" url)
    if(NOT _url MATCHES "^https://[^/?#@ \t\r\n]+([/?#].*)?$")
        message(FATAL_ERROR "Aria deps: ${name}.url must use HTTPS without credentials in '${lock}'")
    endif()
    if(_provider STREQUAL "github")
        string(JSON _revision GET "${_entry}" revision)
        string(LENGTH "${_revision}" _length)
        if(NOT _length EQUAL 40 OR NOT _revision MATCHES "^[0-9a-fA-F]+$")
            message(FATAL_ERROR "Aria deps: ${name}.revision must be a full commit SHA in '${lock}'")
        endif()
    endif()
    string(JSON _artifact GET "${_spec}" artifact)
    if(NOT _artifact STREQUAL "git")
        string(JSON _sha ERROR_VARIABLE _error GET "${_entry}" sha256)
        string(LENGTH "${_sha}" _length)
        if(_error OR NOT _length EQUAL 64 OR NOT _sha MATCHES "^[0-9a-fA-F]+$")
            message(FATAL_ERROR "Aria deps: ${name}.sha256 must be a SHA256 in '${lock}'")
        endif()
    endif()
    set(${valid} TRUE PARENT_SCOPE)
    set(${entry} "${_entry}" PARENT_SCOPE)
endfunction()

# aria_resolve_dependency(NAME json VERSION version URL url SHA256 hash
#                         [REVISION commit] [TAG tag] [MANIFEST path] [LOCK path])
# Output arguments name variables in the caller's scope. NAME is case insensitive.
function(aria_resolve_dependency)
    cmake_parse_arguments(DEP "" "NAME;VERSION;URL;SHA256;REVISION;TAG;MANIFEST;LOCK" "" ${ARGN})
    if(NOT DEP_NAME OR DEP_UNPARSED_ARGUMENTS OR DEP_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "aria_resolve_dependency: expected NAME and output-variable arguments")
    endif()
    string(TOLOWER "${DEP_NAME}" _name)
    string(TOUPPER "${DEP_NAME}" _upper)
    if(NOT DEP_MANIFEST AND ARIA_DEPENDENCY_MANIFEST)
        set(DEP_MANIFEST "${ARIA_DEPENDENCY_MANIFEST}")
    endif()
    if(NOT DEP_LOCK AND ARIA_DEPENDENCY_LOCK)
        set(DEP_LOCK "${ARIA_DEPENDENCY_LOCK}")
    endif()
    if(NOT DEP_MANIFEST)
        set(DEP_MANIFEST "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../dependencies.json")
    endif()
    if(NOT DEP_LOCK)
        get_filename_component(_manifest_dir "${DEP_MANIFEST}" DIRECTORY)
        set(DEP_LOCK "${_manifest_dir}/dependencies.lock.json")
    endif()
    get_filename_component(DEP_MANIFEST "${DEP_MANIFEST}" ABSOLUTE)
    get_filename_component(DEP_LOCK "${DEP_LOCK}" ABSOLUTE)
    if(NOT EXISTS "${DEP_MANIFEST}")
        message(FATAL_ERROR "Aria deps: manifest does not exist: ${DEP_MANIFEST}")
    endif()
    file(READ "${DEP_MANIFEST}" _manifest)
    string(JSON _schema ERROR_VARIABLE _error GET "${_manifest}" schema)
    if(_error OR NOT _schema STREQUAL "1")
        message(FATAL_ERROR "Aria deps: invalid manifest schema: ${DEP_MANIFEST}")
    endif()
    string(JSON _spec ERROR_VARIABLE _error GET "${_manifest}" dependencies "${_name}")
    if(_error)
        message(FATAL_ERROR "Aria deps: '${_name}' is not in ${DEP_MANIFEST}")
    endif()
    set(_requested "${ARIA_DEP_${_upper}_VERSION}")
    set(_explicit TRUE)
    if(_requested STREQUAL "")
        string(JSON _requested ERROR_VARIABLE _error GET "${_spec}" version)
        if(_error OR _requested STREQUAL "")
            set(_requested latest)
            set(_explicit FALSE)
        endif()
    endif()
    # Track the base even when it already satisfies this request. Otherwise
    # deleting a later checked-in lock could resurrect an effective lock from
    # an earlier period when the source lock was absent.
    string(SHA256 _identity "${DEP_MANIFEST}\n${DEP_LOCK}")
    string(SUBSTRING "${_identity}" 0 16 _identity)
    set(_directory "${CMAKE_BINARY_DIR}/deps/aria-${_identity}")
    file(MAKE_DIRECTORY "${_directory}")
    file(LOCK "${_directory}/.cmake-resolve.lock" GUARD FUNCTION TIMEOUT 180)
    set(_effective "${_directory}/dependencies.lock.json")
    string(SHA256 _manifest_hash "${_manifest}")
    set(_base_hash missing)
    if(EXISTS "${DEP_LOCK}")
        file(SHA256 "${DEP_LOCK}" _base_hash)
    endif()
    set(_state "${_manifest_hash}\n${_base_hash}\n")
    set(_previous_state "")
    if(EXISTS "${_directory}/base-state")
        file(READ "${_directory}/base-state" _previous_state)
    endif()
    if(NOT _state STREQUAL _previous_state)
        file(REMOVE "${_effective}")
        file(WRITE "${_directory}/base-state" "${_state}")
    endif()
    _aria_dependency_lock_entry("${DEP_LOCK}" "${_manifest}" "${_name}" "${_requested}" "${_explicit}" _valid _entry)
    if(NOT _valid)
        # Retain the effective selection across configure runs only while
        # its manifest and base lock stay unchanged.
        _aria_dependency_lock_entry("${_effective}" "${_manifest}" "${_name}" "${_requested}" "${_explicit}" _valid _entry)
        if(NOT _valid)
            find_package(Python3 3.10 QUIET COMPONENTS Interpreter)
            if(NOT Python3_Interpreter_FOUND)
                message(FATAL_ERROR
                    "Aria deps: resolving ${_name} (${_requested}) requires Python 3.10+. "
                    "A matching checked-in dependencies.lock.json builds without Python.")
            endif()
            set(_arguments resolve --manifest "${DEP_MANIFEST}" --lock "${_effective}"
                --cache-dir "${_directory}/downloads" --only "${_name}")
            if(EXISTS "${DEP_LOCK}")
                list(APPEND _arguments --base-lock "${DEP_LOCK}")
            endif()
            if(NOT "${ARIA_DEP_${_upper}_VERSION}" STREQUAL "")
                list(APPEND _arguments --version "${_name}=${ARIA_DEP_${_upper}_VERSION}")
            endif()
            if(ARIA_DEPENDENCIES_OFFLINE)
                list(APPEND _arguments --offline)
            endif()
            execute_process(COMMAND "${Python3_EXECUTABLE}"
                "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../scripts/dependencies.py" ${_arguments}
                RESULT_VARIABLE _result OUTPUT_VARIABLE _output ERROR_VARIABLE _error)
            if(NOT _result EQUAL 0)
                message(FATAL_ERROR "Aria deps: resolution failed for ${_name}:\n${_output}${_error}")
            endif()
            _aria_dependency_lock_entry("${_effective}" "${_manifest}" "${_name}" "${_requested}" "${_explicit}" _valid _entry)
            if(NOT _valid)
                message(FATAL_ERROR "Aria deps: resolver did not produce a matching lock for ${_name}")
            endif()
        endif()
    endif()
    if(NOT CMAKE_SCRIPT_MODE_FILE)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            "${DEP_MANIFEST}" "${DEP_LOCK}")
        if(EXISTS "${_effective}")
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_effective}")
        endif()
    endif()
    foreach(_field VERSION URL SHA256 REVISION TAG)
        if(DEP_${_field})
            string(TOLOWER "${_field}" _key)
            string(JSON _value ERROR_VARIABLE _error GET "${_entry}" "${_key}")
            if(_error)
                message(FATAL_ERROR "Aria deps: ${_name} has no ${_key} in its lock entry")
            endif()
            set(${DEP_${_field}} "${_value}" PARENT_SCOPE)
        endif()
    endforeach()
endfunction()
