# Qt is an installed SDK, not a downloaded source dependency. Keep CMake's
# prefix/Qt6_DIR selection explicit and prefer newer visible version folders.
include_guard(GLOBAL)
set(ARIA_DEP_QT_VERSION "" CACHE STRING "Exact installed Qt6 version (empty: newest visible candidate)")

macro(aria_find_qt6)
    set(_aria_qt_order_defined FALSE)
    set(_aria_qt_direction_defined FALSE)
    if(DEFINED CMAKE_FIND_PACKAGE_SORT_ORDER)
        set(_aria_qt_order_defined TRUE)
    endif()
    if(DEFINED CMAKE_FIND_PACKAGE_SORT_DIRECTION)
        set(_aria_qt_direction_defined TRUE)
    endif()
    set(_aria_qt_sort_order "${CMAKE_FIND_PACKAGE_SORT_ORDER}")
    set(_aria_qt_sort_direction "${CMAKE_FIND_PACKAGE_SORT_DIRECTION}")
    set(CMAKE_FIND_PACKAGE_SORT_ORDER NATURAL)
    set(CMAKE_FIND_PACKAGE_SORT_DIRECTION DEC)
    if(ARIA_DEP_QT_VERSION)
        find_package(Qt6 "${ARIA_DEP_QT_VERSION}" EXACT ${ARGN})
    else()
        find_package(Qt6 ${ARGN})
    endif()
    if(_aria_qt_order_defined)
        set(CMAKE_FIND_PACKAGE_SORT_ORDER "${_aria_qt_sort_order}")
    else()
        unset(CMAKE_FIND_PACKAGE_SORT_ORDER)
    endif()
    if(_aria_qt_direction_defined)
        set(CMAKE_FIND_PACKAGE_SORT_DIRECTION "${_aria_qt_sort_direction}")
    else()
        unset(CMAKE_FIND_PACKAGE_SORT_DIRECTION)
    endif()
    unset(_aria_qt_sort_order)
    unset(_aria_qt_sort_direction)
    unset(_aria_qt_order_defined)
    unset(_aria_qt_direction_defined)
endmacro()
