# Provide OpenSSL::SSL and OpenSSL::Crypto for HTTP TLS. A parent can supply
# both targets, or an openssl_external producer plus FindOpenSSL-style paths.
# Otherwise build the vendored source with the active target toolchain.
set(ARIA_BUNDLED_OPENSSL OFF)
if(TARGET OpenSSL::SSL AND TARGET OpenSSL::Crypto)
    message(STATUS "Aria TLS: using parent OpenSSL targets")
    return()
elseif(TARGET OpenSSL::SSL OR TARGET OpenSSL::Crypto)
    message(FATAL_ERROR "Aria TLS requires both OpenSSL::SSL and OpenSSL::Crypto; the parent supplied only one")
endif()

include(ExternalProject)
find_package(Threads REQUIRED)

function(_aria_openssl_system_libraries)
    if(WIN32)
        set_property(TARGET OpenSSL::Crypto APPEND PROPERTY
            INTERFACE_LINK_LIBRARIES ws2_32 gdi32 advapi32 crypt32 user32)
    else()
        set_property(TARGET OpenSSL::Crypto APPEND PROPERTY
            INTERFACE_LINK_LIBRARIES Threads::Threads ${CMAKE_DL_LIBS})
    endif()
endfunction()

if(TARGET openssl_external)
    # Support the aggregate variable too, but never guess an archive's role
    # from its list position (FindOpenSSL can append platform dependencies).
    foreach(_library IN LISTS OPENSSL_LIBRARIES)
        get_filename_component(_name "${_library}" NAME)
        if(_name MATCHES "^(lib)?ssl[.]")
            set(OPENSSL_SSL_LIBRARY "${_library}")
        elseif(_name MATCHES "^(lib)?crypto[.]")
            set(OPENSSL_CRYPTO_LIBRARY "${_library}")
        endif()
    endforeach()
    if(NOT OPENSSL_INCLUDE_DIR OR NOT OPENSSL_SSL_LIBRARY OR NOT OPENSSL_CRYPTO_LIBRARY)
        message(FATAL_ERROR
            "Parent openssl_external must provide OPENSSL_INCLUDE_DIR and "
            "OPENSSL_SSL_LIBRARY/OPENSSL_CRYPTO_LIBRARY (or identifiable archives in OPENSSL_LIBRARIES)")
    endif()
    foreach(_kind SSL Crypto)
        string(TOUPPER "${_kind}" _upper)
        add_library(OpenSSL::${_kind} UNKNOWN IMPORTED GLOBAL)
        set_target_properties(OpenSSL::${_kind} PROPERTIES
            IMPORTED_LOCATION "${OPENSSL_${_upper}_LIBRARY}"
            INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}")
        add_dependencies(OpenSSL::${_kind} openssl_external)
    endforeach()
    set_property(TARGET OpenSSL::SSL PROPERTY INTERFACE_LINK_LIBRARIES OpenSSL::Crypto)
    _aria_openssl_system_libraries()
    set(OPENSSL_FOUND TRUE)
    return()
endif()

set(OPENSSL_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../third_party/openssl")
get_filename_component(OPENSSL_SOURCE_DIR "${OPENSSL_SOURCE_DIR}" ABSOLUTE)
if(NOT EXISTS "${OPENSSL_SOURCE_DIR}/Configure")
    message(FATAL_ERROR
        "ARIA_HTTP_ENABLE_TLS=ON but third_party/openssl/Configure is missing. "
        "Initialize that submodule, provide parent OpenSSL targets, or explicitly disable TLS.")
endif()
# OpenSSL is C code; never substitute a C++ driver in a CXX-only parent.
enable_language(C)
get_filename_component(_OPENSSL_COMPILER_DIR "${CMAKE_C_COMPILER}" DIRECTORY)
get_filename_component(_OPENSSL_CC "${CMAKE_C_COMPILER}" NAME)
get_filename_component(_OPENSSL_AR "${CMAKE_AR}" NAME)
get_filename_component(_OPENSSL_RANLIB "${CMAKE_RANLIB}" NAME)

set(_OPENSSL_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
if(APPLE AND CMAKE_OSX_ARCHITECTURES)
    list(LENGTH CMAKE_OSX_ARCHITECTURES _arch_count)
    if(NOT _arch_count EQUAL 1)
        message(FATAL_ERROR "Vendored OpenSSL requires one Apple architecture per build; use separate builds or parent universal OpenSSL targets")
    endif()
    set(_OPENSSL_ARCH "${CMAKE_OSX_ARCHITECTURES}")
endif()
string(TOLOWER "${_OPENSSL_ARCH}" _OPENSSL_ARCH)
set(_OPENSSL_EXTRA_CFLAGS "")
set(_OPENSSL_EXTRA_ARGS "")
set(_OPENSSL_NDK "")
if(ANDROID)
    if(ANDROID_ABI STREQUAL "arm64-v8a")
        set(_OPENSSL_TARGET android-arm64)
    elseif(ANDROID_ABI STREQUAL "armeabi-v7a")
        set(_OPENSSL_TARGET android-arm)
    elseif(ANDROID_ABI STREQUAL "x86_64")
        set(_OPENSSL_TARGET android-x86_64)
    elseif(ANDROID_ABI STREQUAL "x86")
        set(_OPENSSL_TARGET android-x86)
    elseif(ANDROID_ABI STREQUAL "riscv64")
        set(_OPENSSL_TARGET android-riscv64)
    else()
        message(FATAL_ERROR "Unsupported Android OpenSSL ABI: ${ANDROID_ABI}")
    endif()
    set(_OPENSSL_NDK "${CMAKE_ANDROID_NDK}")
    if(NOT _OPENSSL_NDK)
        set(_OPENSSL_NDK "${ANDROID_NDK}")
    endif()
    if(NOT EXISTS "${_OPENSSL_NDK}/source.properties")
        message(FATAL_ERROR "OpenSSL Android build requires the configured Android NDK")
    endif()
    # The NDK toolchain deliberately sets CMAKE_SYSTEM_VERSION to 1. Its
    # resolved platform level also accounts for ABI minimums and API aliases.
    set(_OPENSSL_API "${ANDROID_PLATFORM_LEVEL}")
    if(NOT _OPENSSL_API MATCHES "^[0-9]+$")
        set(_OPENSSL_API "${ANDROID_NATIVE_API_LEVEL}")
        string(REGEX REPLACE "^android-" "" _OPENSSL_API "${_OPENSSL_API}")
    endif()
    if(NOT _OPENSSL_API MATCHES "^[0-9]+$")
        set(_OPENSSL_API "${CMAKE_SYSTEM_VERSION}")
    endif()
    if(NOT _OPENSSL_API MATCHES "^[0-9]+$" OR _OPENSSL_API LESS 16)
        message(FATAL_ERROR "OpenSSL Android build requires a numeric Android API level")
    endif()
    list(APPEND _OPENSSL_EXTRA_ARGS "-D__ANDROID_API__=${_OPENSSL_API}")
elseif(APPLE)
    if(CMAKE_SYSTEM_NAME STREQUAL "iOS" OR CMAKE_OSX_SYSROOT MATCHES "[iI][pP]hone")
        if(CMAKE_OSX_SYSROOT MATCHES "[sS]imulator")
            if(_OPENSSL_ARCH STREQUAL "arm64")
                set(_OPENSSL_TARGET iossimulator-arm64-xcrun)
            elseif(_OPENSSL_ARCH MATCHES "^(x86_64|amd64)$")
                set(_OPENSSL_TARGET iossimulator-x86_64-xcrun)
            else()
                message(FATAL_ERROR "Unsupported iOS simulator architecture: ${_OPENSSL_ARCH}")
            endif()
            set(_OPENSSL_SDK iphonesimulator)
            set(_OPENSSL_DEPLOYMENT_FLAG -mios-simulator-version-min)
        else()
            if(NOT _OPENSSL_ARCH STREQUAL "arm64")
                message(FATAL_ERROR "Unsupported iOS device architecture: ${_OPENSSL_ARCH}")
            endif()
            set(_OPENSSL_TARGET ios64-xcrun)
            set(_OPENSSL_SDK iphoneos)
            set(_OPENSSL_DEPLOYMENT_FLAG -miphoneos-version-min)
        endif()
    else()
        if(_OPENSSL_ARCH MATCHES "^(arm64|aarch64)$")
            set(_OPENSSL_TARGET darwin64-arm64)
        elseif(_OPENSSL_ARCH MATCHES "^(x86_64|amd64)$")
            set(_OPENSSL_TARGET darwin64-x86_64)
        else()
            message(FATAL_ERROR "Unsupported macOS OpenSSL architecture: ${_OPENSSL_ARCH}")
        endif()
        set(_OPENSSL_SDK macosx)
        set(_OPENSSL_DEPLOYMENT_FLAG -mmacosx-version-min)
    endif()
    if(IS_DIRECTORY "${CMAKE_OSX_SYSROOT}")
        set(_OPENSSL_SDK_PATH "${CMAKE_OSX_SYSROOT}")
    else()
        execute_process(COMMAND xcrun --sdk "${_OPENSSL_SDK}" --show-sdk-path
            OUTPUT_VARIABLE _OPENSSL_SDK_PATH OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _sdk_result)
        if(NOT _sdk_result EQUAL 0)
            message(FATAL_ERROR "Unable to resolve the Apple SDK for OpenSSL")
        endif()
    endif()
    string(APPEND _OPENSSL_EXTRA_CFLAGS " -isysroot \"${_OPENSSL_SDK_PATH}\"")
    if(CMAKE_OSX_DEPLOYMENT_TARGET)
        string(APPEND _OPENSSL_EXTRA_CFLAGS " ${_OPENSSL_DEPLOYMENT_FLAG}=${CMAKE_OSX_DEPLOYMENT_TARGET}")
    endif()
elseif(MSVC)
    if(_OPENSSL_ARCH MATCHES "^(arm64|aarch64)$" OR CMAKE_GENERATOR_PLATFORM STREQUAL "ARM64")
        set(_OPENSSL_TARGET VC-WIN64-ARM)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(_OPENSSL_TARGET VC-WIN64A)
    else()
        set(_OPENSSL_TARGET VC-WIN32)
    endif()
    if(CMAKE_MSVC_RUNTIME_LIBRARY AND NOT CMAKE_MSVC_RUNTIME_LIBRARY MATCHES "DLL")
        list(APPEND _OPENSSL_EXTRA_ARGS enable-static-vcruntime)
    endif()
elseif(MINGW)
    if(_OPENSSL_ARCH MATCHES "^(arm64|aarch64)$")
        set(_OPENSSL_TARGET mingwarm64)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(_OPENSSL_TARGET mingw64)
    else()
        set(_OPENSSL_TARGET mingw)
    endif()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    if(_OPENSSL_ARCH MATCHES "^(arm64|aarch64)$")
        set(_OPENSSL_TARGET linux-aarch64)
    elseif(_OPENSSL_ARCH MATCHES "^(x86_64|amd64)$")
        set(_OPENSSL_TARGET linux-x86_64)
    elseif(_OPENSSL_ARCH MATCHES "^i[3-6]86$")
        set(_OPENSSL_TARGET linux-x86)
    elseif(_OPENSSL_ARCH MATCHES "^arm")
        set(_OPENSSL_TARGET linux-armv4)
    elseif(_OPENSSL_ARCH STREQUAL "riscv64")
        set(_OPENSSL_TARGET linux64-riscv64)
    else()
        message(FATAL_ERROR "Unsupported Linux OpenSSL architecture: ${_OPENSSL_ARCH}; provide parent OpenSSL targets")
    endif()
else()
    message(FATAL_ERROR "Unsupported vendored OpenSSL platform: ${CMAKE_SYSTEM_NAME}; provide parent OpenSSL targets")
endif()
if(NOT MSVC)
    string(APPEND _OPENSSL_EXTRA_CFLAGS " -fPIC")
endif()

set(_OPENSSL_BASH "")
if(CMAKE_HOST_WIN32 AND MINGW)
    # Upstream supports MinGW builds through a complete MSYS2 toolchain.
    # Do not mix mingw32-make/cmd.exe with MSYS Perl and Unix recipes.
    find_program(ARIA_OPENSSL_BASH NAMES bash
        HINTS "${_OPENSSL_COMPILER_DIR}/../../usr/bin" "${_OPENSSL_COMPILER_DIR}/../usr/bin"
        REQUIRED NO_CMAKE_FIND_ROOT_PATH)
    get_filename_component(_msys_bin "${ARIA_OPENSSL_BASH}" DIRECTORY)
    find_program(ARIA_OPENSSL_PERL NAMES perl HINTS "${_msys_bin}" REQUIRED NO_DEFAULT_PATH)
    find_program(ARIA_OPENSSL_MAKE NAMES make HINTS "${_msys_bin}" REQUIRED NO_DEFAULT_PATH)
    set(_OPENSSL_BASH "${ARIA_OPENSSL_BASH}")
else()
    find_program(ARIA_OPENSSL_PERL NAMES perl REQUIRED NO_CMAKE_FIND_ROOT_PATH)
    if(MSVC)
        find_program(ARIA_OPENSSL_MAKE NAMES nmake REQUIRED NO_CMAKE_FIND_ROOT_PATH)
        if(NOT _OPENSSL_TARGET STREQUAL "VC-WIN64-ARM")
            find_program(ARIA_OPENSSL_NASM NAMES nasm REQUIRED NO_CMAKE_FIND_ROOT_PATH)
            get_filename_component(_OPENSSL_NASM_DIR "${ARIA_OPENSSL_NASM}" DIRECTORY)
        endif()
    else()
        find_program(ARIA_OPENSSL_MAKE NAMES gmake make REQUIRED NO_CMAKE_FIND_ROOT_PATH)
    endif()
endif()
set(ARIA_OPENSSL_JOBS 4 CACHE STRING "Parallel jobs for the vendored OpenSSL build")
if(NOT ARIA_OPENSSL_JOBS MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "ARIA_OPENSSL_JOBS must be a positive integer")
endif()

file(STRINGS "${OPENSSL_SOURCE_DIR}/VERSION.dat" _version_lines REGEX "^(MAJOR|MINOR|PATCH)=")
foreach(_line IN LISTS _version_lines)
    if(_line MATCHES "^([A-Z]+)=([0-9]+)$")
        set(_OPENSSL_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
    endif()
endforeach()
set(OPENSSL_VERSION "${_OPENSSL_MAJOR}.${_OPENSSL_MINOR}.${_OPENSSL_PATCH}")
set(_OPENSSL_ROOT "${CMAKE_CURRENT_BINARY_DIR}/_deps/aria-openssl")
set(_OPENSSL_CONFIG "$<IF:$<BOOL:$<CONFIG>>,$<CONFIG>,Release>")
set(OPENSSL_INSTALL_DIR "${_OPENSSL_ROOT}/install/${_OPENSSL_CONFIG}")
set(_OPENSSL_CONFIGURE_ARGS "${_OPENSSL_TARGET}" no-shared no-module no-tests no-apps no-docs no-comp no-dtls no-engine no-legacy ${_OPENSSL_EXTRA_ARGS})
file(MAKE_DIRECTORY "${_OPENSSL_ROOT}")
configure_file("${CMAKE_CURRENT_LIST_DIR}/RunOpenSSL.cmake.in" "${_OPENSSL_ROOT}/run.cmake" @ONLY)
if(_OPENSSL_BASH)
    configure_file("${CMAKE_CURRENT_LIST_DIR}/RunOpenSSL-mingw.sh.in" "${_OPENSSL_ROOT}/run-mingw.sh" @ONLY)
endif()
if(MSVC)
    set(_OPENSSL_SSL_NAME libssl.lib)
    set(_OPENSSL_CRYPTO_NAME libcrypto.lib)
else()
    set(_OPENSSL_SSL_NAME libssl.a)
    set(_OPENSSL_CRYPTO_NAME libcrypto.a)
endif()
ExternalProject_Add(aria_openssl_external
    SOURCE_DIR "${OPENSSL_SOURCE_DIR}"
    PREFIX "${_OPENSSL_ROOT}/external"
    CONFIGURE_COMMAND "${CMAKE_COMMAND}" "-DCONFIG=${_OPENSSL_CONFIG}" -DSTEP=configure -P "${_OPENSSL_ROOT}/run.cmake"
    BUILD_COMMAND "${CMAKE_COMMAND}" "-DCONFIG=${_OPENSSL_CONFIG}" -DSTEP=build -P "${_OPENSSL_ROOT}/run.cmake"
    INSTALL_COMMAND "${CMAKE_COMMAND}" "-DCONFIG=${_OPENSSL_CONFIG}" -DSTEP=install -P "${_OPENSSL_ROOT}/run.cmake"
    BUILD_BYPRODUCTS "${OPENSSL_INSTALL_DIR}/lib/${_OPENSSL_SSL_NAME}" "${OPENSSL_INSTALL_DIR}/lib/${_OPENSSL_CRYPTO_NAME}"
    LOG_CONFIGURE TRUE LOG_BUILD TRUE LOG_INSTALL TRUE)
ExternalProject_Add_StepDependencies(aria_openssl_external configure
    "${_OPENSSL_ROOT}/run.cmake")
if(_OPENSSL_BASH)
    ExternalProject_Add_StepDependencies(aria_openssl_external configure
        "${_OPENSSL_ROOT}/run-mingw.sh")
endif()

set(_configs Release Debug RelWithDebInfo MinSizeRel ${CMAKE_CONFIGURATION_TYPES} ${CMAKE_BUILD_TYPE})
list(REMOVE_DUPLICATES _configs)
foreach(_kind SSL Crypto)
    string(TOUPPER "${_kind}" _upper)
    add_library(OpenSSL::${_kind} STATIC IMPORTED GLOBAL)
    set_target_properties(OpenSSL::${_kind} PROPERTIES
        IMPORTED_LOCATION "${_OPENSSL_ROOT}/install/Release/lib/${_OPENSSL_${_upper}_NAME}"
        INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INSTALL_DIR}/include")
    foreach(_config IN LISTS _configs)
        string(TOUPPER "${_config}" _config_upper)
        file(MAKE_DIRECTORY "${_OPENSSL_ROOT}/install/${_config}/include")
        set_property(TARGET OpenSSL::${_kind} APPEND PROPERTY IMPORTED_CONFIGURATIONS "${_config}")
        set_property(TARGET OpenSSL::${_kind} PROPERTY "IMPORTED_LOCATION_${_config_upper}"
            "${_OPENSSL_ROOT}/install/${_config}/lib/${_OPENSSL_${_upper}_NAME}")
    endforeach()
    add_dependencies(OpenSSL::${_kind} aria_openssl_external)
endforeach()
set_property(TARGET OpenSSL::SSL PROPERTY INTERFACE_LINK_LIBRARIES OpenSSL::Crypto)
_aria_openssl_system_libraries()
set(OPENSSL_FOUND TRUE)
set(ARIA_BUNDLED_OPENSSL ON)
message(STATUS "Aria TLS: vendored OpenSSL ${OPENSSL_VERSION}, target ${_OPENSSL_TARGET}")
