# Platform detection — sets cache variables ARIA_PLATFORM_*

set(ARIA_PLATFORM_DESKTOP OFF)
set(ARIA_PLATFORM_MOBILE OFF)
set(ARIA_PLATFORM_WEB OFF)

if(EMSCRIPTEN)
    set(ARIA_PLATFORM_NAME "Web")
    set(ARIA_PLATFORM_WEB ON)
elseif(ANDROID)
    set(ARIA_PLATFORM_NAME "Android")
    set(ARIA_PLATFORM_MOBILE ON)
elseif(IOS)
    set(ARIA_PLATFORM_NAME "iOS")
    set(ARIA_PLATFORM_MOBILE ON)
elseif(APPLE)
    set(ARIA_PLATFORM_NAME "macOS")
    set(ARIA_PLATFORM_DESKTOP ON)
elseif(WIN32)
    set(ARIA_PLATFORM_NAME "Windows")
    set(ARIA_PLATFORM_DESKTOP ON)
elseif(UNIX)
    set(ARIA_PLATFORM_NAME "Linux")
    set(ARIA_PLATFORM_DESKTOP ON)
else()
    set(ARIA_PLATFORM_NAME "Unknown")
endif()

message(STATUS "aria: platform = ${ARIA_PLATFORM_NAME}")
